name: Super-linterxxx

on: push
#on: triger the event
#need to have a space!
jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Sub-linter
        uses: github/super-linter@v4.10.1
        env:
          Default_Branch: main
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
